### ISSUE TITLE
Collect Bio of new members

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/open-community-building#1]
Following new members will be introduced to different teams via email, hence, we are collecting their bio that could be sent around:

- [x] Vicky Hellon
- [x] Achintya Rao
- [x] Arron Lacey

**Comment by malvikasharan** [comment]
Vicky Hellon is the Community Manager for the recently launched Turing-Roche Partnership. She will be working closely with both organisations to build an engaged and sustainable community around the partnership, with a focus on supporting researchers to embrace and embed Open Science practices.
 
Vicky has a BSc in Biomedical Science from the University of Sheffield and previously had roles in Open Access publishing at Springer Nature and F1000Research. At F1000Research she worked in researcher outreach, particularly in Bioinformatics communities and also delivered Open Access publishing services for funders and institutions, most notably as project lead for HRB Open Research and NIHR Open Research. More recently she worked at Health Data Research UK, building a community around the newly launched Health Data Research Innovation Gateway, a portal to help researchers discover and request access to UK health datasets.
 
She is passionate about supporting forward-thinking changes to the academic publishing system and engaging with researchers from a range of backgrounds.

**Comment by malvikasharan** [comment]
@RaoOfPhysics can you please see if you'd like to add something else to your bio?
> Achintya Rao is the Community Manager for the AI for Science and Government research programme. As a science communicator for over a decade, he brings a range of experience from working at CERN, the European Organization for Nuclear Research. He has a Bachelors degree in physics from St Xavier’s College, Bombay and an MA in science journalism from City University London. He is pursuing a PhD in science communication from the University of the West of England, in Bristol. 
> In what spare time he has, he enjoys watching and playing cricket and reading and tinkering with technology.

**Comment by RaoOfPhysics** [comment]
Hi @malvikasharan! Saw the notification yesterday but didn't have the time to send you something. Apologies for that.

How about this (slight edits)?

> Achintya Rao is the Community Manager for the AI for Science and Government research programme. He has a backgrond in science communication, with over a decade of experience working at CERN, the European Organization for Nuclear Research, where, among other things, he helped communicate the discovery of the Higgs boson at the Large Hadron Collider and also contributed to the CERN Open Data portal. He has a BSc in physics from St Xavier’s College, Mumbai, and an MA in science journalism from City University London; he is pursuing a PhD in science communication from the University of the West of England, in Bristol.
>
> He is enthusiastic about public engagement with research as well as open and reproducible science, enjoys watching and playing cricket, and can spend hours tinkering with new technologies.

**Comment by malvikasharan** [comment]
@arronlacey I have given you write access to this repo. Meanwhile, can you please add your bio here?

**Comment by arronlacey** [comment]
Arron Lacey is the Senior Community Manager for the Early Detection of Neurodegenerative Diseases (EDoN) project. Arron will be mainly based in the Analytics Hub to contribute to data and machine learning pipelines that aim to train models to predict Mild Cognitive Impairment (MCI). Patients are recruited to use wearables (fit bits, sleep bands etc) to passively monitor various metrics that could provide "fingerprints" of what pre-clinical MCI looks like, and are followed up prospectively to map patient trajectories. This remit also includes a commitment to Open Science, reproducibility and effective communication across all EDoN hubs and at external events.

Arron holds a BSc in Physics, an MSc and MRes in Computer Science and a PhD in Health Data Science. He was a senior Data Scientist at Swansea University between 2011-2018 before becoming a Lecturer in 2019. He is now an Honorary Lecturer following his appointment at the Alan Turning Institute. His research interests are epidemiology, machine learning and Natural Language Processing where he lead the www.getmarkup.com clinical notes annotation project.

**Comment by arronlacey** [comment]
@malvikasharan all done!

**Comment by malvikasharan** [comment]
Bios are included in the Turing page: https://www.turing.ac.uk/research/research-programmes/tools-practices-and-systems/community-management-and-open-research

@BrainonSilicon can you please place a request via Mathison to add your bio on the webpage?
