### ISSUE TITLE
sktime

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/open-community-building#101]
The sktime project is the largest open community in the alan-turing-institute org, and one of the most international and impactful ones.
https://github.com/alan-turing-institute/sktime

We haven't been approached or contacted by this "open community building" project, or involved in its construction. Bit odd, but I suppose everyone has been busy, and the onus to get in contact is not just with you.

Are you interested in making contact?

On a side note, I'm not sure to which extent you are following a "top-down" approach here, e.g., to which extent one needs to commit to "follow the lead" of your management structure to be involved, and to what extent your leadership is cast in stone. I'm not sure I currently understand your joining process?

"Follow the project lead" would not be a very "open" philosophy, i.e., if you insist on hard-coded "ownership" in the projects joining.
The open opposite would be having specified, open and transparent governance rules, about how one can become a leader in your community, up to and including the "project lead" type of role that currently only @malvikasharan inhabits.

In my opinion, no community without transparent, open governance is truly "open", no matter how often the word "open" appears in the brand pack.
sktime does not plaster its readme full of the word "open" but strives to *be* open. See our governance:
https://www.sktime.org/en/stable/get_involved/governance.html#governance
The crux about "openness" is in how leaders are elected and how they are accountable with their decisions and allocation of resources, to the community. Where openness truly matters is in decision making, allocation of resources, and other aspects of "power".

Openness is very similar to D&I, the concerns of which you are surely familiar with - using the D&I language all over the place is one thing, every organisation does that these days. But, the "true" litmus test is whether people from underrepresented groups are given actual power, e.g., in the form of promotions, equal pay, grant money, professional visibility, and the like.

But those are finer points we can surely discuss once our communities get in contact.
Any good times in the next months?

**Comment by malvikasharan** [comment]
Also, I am happy to chat with you about the open source in detail, but maybe https://github.com/alan-turing-institute/the-turing-way is a better place for that, which I co-lead with Kirstie. You can join us for the coworking call on Monday to chat: https://hackmd.io/@turingway/coworking-calls, See you. Say hi to @mloning.

**Comment by fkiraly** [comment]
> Would you like to be involved? https://github.com/alan-turing-institute/open-community-building#open-research-community-building-team

That link does not lead anywhere

**Comment by fkiraly** [comment]
>Fun fact, Kirstie and I consulted Markus on sktime community governance, which was funded under TPS (where the team of Community Managers sit, who this repo addresses), in fact, sktime went through Open Life Science training programme (I am co-director of OLS) to build their community plans, under the mentorship of The Turing Way core member. We are very huge supporters of Markus' collaborative work and glad to see you advocating for that.

Yes, that´s indeed a fun fact - why are our communities then not in direct contact and exchange?

**Comment by malvikasharan** [comment]
Hi Franz, Markus was actively collaborating with us in The Turing Way and working with Kirstie while he was at the Turing. He had also made connections between our community, for instance, some project documents of sktime reuse The Turing Way materials, and some of sktime community members/GSoC interns have also undergone Open Life Science training and contributed to The Turing Way. 

I think you are approaching a useful conversation that is not relevant to this repository but should be taken to The Turing Way. I can see why you would have assumed that this team is volunteer-based - all members in this repository are paid staff of TPS under the community management team (like the Research Engineering group at the Turing Institute). I am sharing more details from my team to clarify that for you (yes! I am a team lead of the community management team as a senior researcher because that is my job responsibility and as an Indian woman + an immigrant I don't need to be taught what advocating for EDI means.).

> The [Tools, Practices and Systems (TPS)](https://www.turing.ac.uk/research/research-programmes/tools-practices-and-systems) programme at The Alan Turing Institute under the leadership of Dr. Kirstie Whitaker represents a cross-cutting set of initiatives which seek to build open source infrastructure that is accessible to all and to empower a global, decentralised network of people who connect data with domain experts.
> 
> Led by Dr. Malvika Sharan, TPS Senior Researcher for Open Research, TPS hosts a team of Community Managers funded by different projects at the Institute. All Community Managers are brought together as the [Open Research Community Building](https://www.turing.ac.uk/research/research-programmes/tools-practices-and-systems/community-management-and-open-research) team. Members from within the Turing programmes working in similar positions, as well as members from projects collaborating with TPS/The Turing Way outside the Turing, referred to as "collaborators in community roles" in this document, are also invited to join this team.
> 
> All members of this team also participate in [The Turing Way](https://the-turing-way.netlify.app/welcome) -- an Open Source, Open Collaboration and Community-driven guide to data science co-led by Kirstie (who is also the founder of the project) and Malvika. A part (~10%) of Community Managers' role involves engaging with and contributing to The Turing Way as core staff members of the project. Anyone interested in the work of this team from outside the Turing or non-collaborators is invited to collaborate with us on The Turing Way. For further questions and information, please get in touch with Malvika by emailing [msharan@turing.ac.uk](mailto:msharan@turing.ac.uk).
