### ISSUE TITLE
Plan regular meetings for the team

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/open-community-building#11]
### Summary Sentence

I would like to set up a regular meeting for the community managers.
These meetings should help us learn about others projects, discuss community and Open Research practices and find opportunities for collaborations.

## Why?

Members of this team:
- foster diverse Communities of Practice within and outside the Turing through community building and engagement roles in their respective projects.
- contribute toward building interconnected systems of open source software, datasets, communities and processes". <-- This can only happen if we have dedicated spaces and channels explicitely designed for these connection to emerge.

Specificaly, we have three different nature of participation in this team and we need to make an effort to bring them all at the same speace to build an understanding for collaboration and learning:
- Community Managers at Turing I line manage
- Community Managers at Turing who are line managed by their respective project lead
- Members who are working on projects with community development responsibilities (they may not be employed at the Turing but work with me on formal collaboration)

### What needs to be done?

- [ ] Ask for their preference for the meeting slot
- [ ] Ask for how often (choose between "Weekly" or "Fortnightly"
- [ ] Review the team meeting document and leave any feedback for improvements: https://github.com/alan-turing-institute/open-community-building/blob/main/project-management/team-meetings.md
- [ ] Ask for opinions on the HackMD (see comments from Kirstie below) to remove any overlap with what many of them already do in the Whitaker Lab meetings
- [ ] Set a first meeting in Feb

#### Suggestion for the questions to ask in the weekly HackMD

Kirstie suggested a few questions that can replace the current questions suggested for the HackMD in the team meeting document

- What about asking questions specifically about their communities?
- What did you learn from a community member this week?
- What did you teach a community member this week?
- What open questions do you have from your community?

### Who can help?

All members of this team should copy-paste this checklist and respond below

- [ ] Added preference for the meeting slot
- [ ] Choose between "Weekly" or "Fortnightly"
- [ ] Check this if you have already read this: https://github.com/alan-turing-institute/open-community-building/blob/main/project-management/team-meetings.md
- [ ] Add your comment and suggestion for the HackMD
- [ ] Add any additional notes

---

### Update after the issue was opened

[Add details]

**Comment by vhellon** [comment]
- [X] Added preference for the meeting slot
- [X] Choose between "Weekly" or "Fortnightly"
- [X] Check this if you have already read this: https://github.com/alan-turing-institute/open-community-building/blob/main/project-management/team-meetings.md
- [X] Add your comment and suggestion for the HackMD.

HackMD suggestions:

As my community isn't fully up and running yet, would probably struggle to answer the questions around 'what did you learn/teach a community member' at the moment. 

Do like the 'open questions from your community' prompt.

Maybe could add something like 'what are your upcoming plans (next few weeks) for community engagement', 'any pain points/tension in your community this week'

**Comment by malvikasharan** [comment]
Old issue, task completed.
