### ISSUE TITLE
TYPO: Typo on line 29 of CONTRIBUTING.md

### ISSUE THREAD

**Issue by BrainonSilicon** [alan-turing-institute/open-community-building#113]
### Summary Sentence

There is a typo on line 29 in the heading of the CONTRIBUTING file (linked [here](https://github.com/alan-turing-institute/open-community-building/blob/main/CONTRIBUTING.md#-i-want-to-regularly-to-this-repository-and-i-am-ready-to-contribute-))

### What needs to be done?
- [ ] Correct the typo in the sentence above to reflect what is being asked. 
I am unsure what the heading is meant to read as, however the heading currently reads 
> `I want to regularly to this repository and I am ready to contribute`. 

### Who can help?

@malvikasharan (owner of the CONTRIBUTING document)

---

**Comment by malvikasharan** [comment]
Thanks @BrainonSilicon. This repo belongs to all members of the CM team, and from the perspective I encourage you to directly propose any changes in the future.

**Comment by BrainonSilicon** [comment]
Fantastic! Will take this on 🎉  I wasn't sure if it was a core piece of documentation that was open to edit so thank you for clarifying 🚀
