### ISSUE TITLE
[INDUCTION] For AIM RSF community manager EZ - June

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/open-community-building#46]
# Turing Community Managers Induction and Onboarding - checklist

- [x] Working from home equipment 
    - [x] Laptop
    - [x] Monitor 
    - [x] Peripherals (keyboard, mouse, camera, microphone) 
    - [x] Any other WfH equipment required (eligibility for expenses to check with HR)
- [x] HR induction
- [x] IT induction
- [x] Project manager meeting (onboarding on the project)
- [x] Setting expectation for when we meet
    - [x] 1:1 meetings
        - [x] TPS Director (KW currently on maternity leave)
        - [x] Programme Manager
        - [x] Project Manager
        - [x] Community Building Team
        - [x] Other project stakeholders
        - [x] Business team
        - [x] REG team
        - [x] Training Team
        - [x] RAM Team
    - [x] Fortnightly meetings
    - [x] Informal chats details
    - [x] Access to group repo, docs and calendars
    - [x] Introduce TPS projects
        - [x] The Turing Way (core membership onboarding), see [Ways of Working](https://github.com/alan-turing-institute/the-turing-way/blob/main/ways_of_working.md)
        - [x] Open Life Science
- [x] Slack channels and workspaces
    - [x] Add them to relevant channels and workspace
- [x] Events
    - [x] Send calendar invite of Collaboration Cafe
    - [ ] The Turing Way reading group and book clubs
    - [x] TPS coffee chats
- [x] Their bio and project details to add on the Turing website
- [x] Make introductions with the following people
        - [ ] Training team
        - [ ] REG team
        - [ ] Whitaker lab
        - [ ] TPS
        - [ ] Communications Team 
        - [ ] Relevant Programme Management Team member (e.g. Harriet/Hannah)
        - [ ] Relevant Partnerships Team member 
        - [ ] Relevant Events Team member 
- [x] Documents/ locations to share with them? 
	- [x] Sharepoint
	- [x] Turing Complete
	- [x] GitHub
	- [x] HackMD
	- [x] Turing projects
- [x] Request for bio via Topdesk

**Comment by malvikasharan** [comment]
@EKaroune @evelinag I have created a 1:1 meeting folder for @Eirini_zormpa: https://github.com/alan-turing-institute/open-community-building/tree/main/project-management/1-1-meetings/eirini-zormpa

**Comment by malvikasharan** [comment]
CM team info: https://hackmd.io/@cm-team/link-of-links

**Comment by EKaroune** [comment]
I've had an initial meeting with @eirini-zormpa in which we did intros, I chevked that all going ok, discussed the health community managers and 1 to 1 meetings in more detail. We have arranged our regular 1 to 1 meetings for tuesdays at 10am starting next week.

**Comment by malvikasharan** [comment]
Checking with @eirini-zormpa if we missed anything for her induction (please also read the README page and related details).

**Comment by eirini-zormpa** [comment]
I've updated the checklist now! I don't know about The Turing Way reading group and book clubs?
