### ISSUE TITLE
Collate training materials from previous workshops

### ISSUE THREAD

**Issue by eirini-zormpa** [alan-turing-institute/open-community-building#85]
### Summary Sentence
It'd be useful to collect the training materials from previous workshops Community Managers have run to:
- get an idea of what topics we can easily cover
- avoid duplicating effort

Thank you @EKaroune for the suggestion 🙏 ✨ 

### What needs to be done?
- Have we already tried doing this before?
- To begin with, decide whether we want to just make a list of resources or rework them into a Carpentries-style lesson or add to the Turing Moodle
- The rest will depend on how we've decided to proceed!
 
### Who can help?

- @malvikasharan probably has insight into how time-consuming it would be to rework materials?
- anyone who'd like to help me figure out how best to go about this
- everyone who has taught workshops to contribute materials!

---

### Update after the issue was opened

**Update from Community team meeting on 7 July 2022**

*To-do list:*

- [x] Create a `workshops` directory
- [x] Create a file with a table of courses like [here](https://github.com/alan-turing-institute/open-community-building/blob/main/project-management/resources-for-reference.md), including information on audience level, talk/workshop/course duration, and (ideally) learning outcomes
- [ ] Populate table with already existing resources, adding the link to the slides or materials
- [ ] Create a `templates` folder for slides (markdown/Rmarkdown/quarto). It'd be great if the slides could have consistent branding, e.g. making sure that we always mention the Turing Way

*Discussion topics:*

- Would a calendar of events be helpful?
- How to best get feedback from workshop attendees? Pre/post-workshop survey? Try to get feedback during the session? Can we/should we try to standardise our approach?

**Update from meeting with REG on 12 July 2022**
There are two courses that REG offer regularly: [Research Data Science](https://alan-turing-institute.github.io/rds-course/modules/m1/hands-on.html) and [Research Software Engineering with Python](https://alan-turing-institute.github.io/rse-course/html/index.html). Both are in Python, but the Research Data Science one would be easier to translate to R.

**Comment by eirini-zormpa** [comment]
I've assigned the people who were in the meeting, feel free to unassign yourself if you'd rather not be involved :joy: And the other way around of course, please join us in this if you're interested :sparkles:

**Comment by eirini-zormpa** [comment]
I was also curious if people have opinions about whether it'd make sense to archive any unarchived resources in this directory or if it'd be better to always put things on Zenodo to get a DOI and just link to them here!

**Comment by malvikasharan** [comment]
@eirini-zormpa picking this thread to check if it still worth collating them here or we provide links to resources like the CM Team output doc, especially the [sheet-3](https://docs.google.com/spreadsheets/d/1pegEKZe0l6txwvJi1w8BB2OMzH3ov7tASH8ziC8xg5k/edit#gid=0) (only accessible for CM team members due to sensitive info. In The Turing Way by one of the working groups have also collected all workshop materials. @aleesteele can you please share that resource?
